"""Regression tests for the SSH command wrapper generated by the deploy workflow."""

import os
from pathlib import Path
import subprocess
import tempfile
import unittest


WORKFLOW = Path(__file__).resolve().parents[1] / ".github/workflows/django-deploy-runner.yml"
REMOTE_COMMAND = "deploy main --env staging"
PRUNE_COMMAND = "docker system prune -a -f"


def generated_run_script():
    lines = WORKFLOW.read_text().splitlines()
    marker = "cat > run.sh <<'EOF'"
    start = next(i for i, line in enumerate(lines) if line.strip() == marker)
    indentation = lines[start][: -len(lines[start].lstrip())]
    end = next(i for i in range(start + 1, len(lines)) if lines[i] == indentation + "EOF")
    return "\n".join(line.removeprefix(indentation) for line in lines[start + 1 : end]) + "\n"


STUB = """#!/bin/bash
printf '%s\\n' "$*" >> "$CALLS"
count=$(( $(wc -l < "$CALLS") ))
case "$SCENARIO:$count" in
  success:1|disk_full_retry:3)
    echo 'private deploy success details'
    exit 0 ;;
  disk_full_retry:1|prune_failure:1|retry_failure:1|other_label_disk_full:1)
    echo 'error: unable to create temporary file: No space left on device'
    exit 11 ;;
  disk_full_retry:2|retry_failure:2)
    echo 'private prune success details'
    exit 0 ;;
  prune_failure:2)
    echo 'prune failed: daemon unavailable'
    exit 12 ;;
  retry_failure:3)
    echo 'retry failed: permission denied'
    exit 13 ;;
  unrelated_failure:1)
    echo 'unrelated deploy error'
    exit 14 ;;
  incidental_disk_full:1)
    echo 'warning: old incident: No space left on device'
    echo 'unrelated deploy error'
    exit 15 ;;
esac
echo "unexpected invocation: $SCENARIO:$count" >&2
exit 99
"""


class DeployRunnerTests(unittest.TestCase):
    def run_scenario(self, scenario, label="deploy"):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "run.sh").write_text(generated_run_script())
            (root / "s.sh").write_text(STUB)
            (root / "run.sh").chmod(0o755)
            (root / "s.sh").chmod(0o755)
            calls = root / "calls"
            env = {**os.environ, "SCENARIO": scenario, "CALLS": str(calls)}
            result = subprocess.run(
                ["./run.sh", label, REMOTE_COMMAND],
                cwd=root,
                env=env,
                capture_output=True,
                text=True,
                check=False,
            )
            return result, calls.read_text().splitlines()

    def test_success_hides_remote_output(self):
        result, calls = self.run_scenario("success")
        self.assertEqual(result.returncode, 0)
        self.assertEqual(calls, [REMOTE_COMMAND])
        self.assertEqual(result.stdout, "deploy: ok\n")
        self.assertEqual(result.stderr, "")

    def test_disk_full_prunes_then_retries_once_and_hides_remote_output(self):
        result, calls = self.run_scenario("disk_full_retry")
        self.assertEqual(result.returncode, 0)
        self.assertEqual(calls, [REMOTE_COMMAND, PRUNE_COMMAND, REMOTE_COMMAND])
        self.assertIn("pruning unused Docker data", result.stdout)
        self.assertIn("deploy: ok after Docker prune", result.stdout)
        self.assertNotIn("private", result.stdout + result.stderr)
        self.assertNotIn("No space left on device", result.stdout + result.stderr)

    def test_prune_failure_reports_both_errors_and_propagates_status(self):
        result, calls = self.run_scenario("prune_failure")
        self.assertEqual(result.returncode, 12)
        self.assertEqual(calls, [REMOTE_COMMAND, PRUNE_COMMAND])
        self.assertIn("error: unable to create temporary file: No space left on device", result.stderr)
        self.assertIn("prune failed: daemon unavailable", result.stderr)
        self.assertIn("Docker prune: FAILED", result.stderr)

    def test_retry_failure_reports_both_errors_and_propagates_status(self):
        result, calls = self.run_scenario("retry_failure")
        self.assertEqual(result.returncode, 13)
        self.assertEqual(calls, [REMOTE_COMMAND, PRUNE_COMMAND, REMOTE_COMMAND])
        self.assertIn("error: unable to create temporary file: No space left on device", result.stderr)
        self.assertIn("retry failed: permission denied", result.stderr)
        self.assertIn("deploy: retry FAILED", result.stderr)
        self.assertNotIn("private prune success", result.stdout + result.stderr)

    def test_unrelated_deploy_failure_does_not_prune(self):
        result, calls = self.run_scenario("unrelated_failure")
        self.assertEqual(result.returncode, 14)
        self.assertEqual(calls, [REMOTE_COMMAND])
        self.assertIn("unrelated deploy error", result.stderr)
        self.assertIn("deploy: FAILED", result.stderr)

    def test_incidental_disk_full_message_does_not_prune(self):
        result, calls = self.run_scenario("incidental_disk_full")
        self.assertEqual(result.returncode, 15)
        self.assertEqual(calls, [REMOTE_COMMAND])
        self.assertIn("unrelated deploy error", result.stderr)

    def test_disk_full_on_another_label_does_not_prune(self):
        result, calls = self.run_scenario("other_label_disk_full", label="migrate")
        self.assertEqual(result.returncode, 11)
        self.assertEqual(calls, [REMOTE_COMMAND])
        self.assertIn("error: unable to create temporary file: No space left on device", result.stderr)
        self.assertIn("migrate: FAILED", result.stderr)


if __name__ == "__main__":
    unittest.main()
